BUILD: Fix linking of ini_augment_ut_check
libref_array was used in the unit test but it was mot linked with
libref_array
  CCLD     ini_augment_ut_check
/usr/bin/ld: ini/ini_augment_ut_check-ini_augment_ut_check.o:
    undefined reference to symbol 'ref_array_destroy@@REF_ARRAY_0.1.1'
.libs/libref_array.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1287: ini_augment_ut_check] Error 1

Reviewed-by: Michal Židek <mzidek@redhat.com>

Merges: https://pagure.io/SSSD/ding-libs/pull-request/3179